<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'role',
        'is_active',
        'avatar',
        'google_id',
        'facebook_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password'          => 'hashed',
            'is_active'         => 'boolean',
            'deleted_at'        => 'datetime',
        ];
    }

        ];
    }

    // ==================== HELPERS ====================

    /**
     * Check whether this user is an admin.
     */
    public function isAdmin(): bool
    {
        return $this->role === 'admin';
    }

    // ---------- Relationships ----------

    /**
     * Pets owned by this user.
     */
    public function pets(): HasMany
    {
        return $this->hasMany(Pet::class);
    }

    /**
     * Reminders belonging to this user.
     */
    public function reminders(): HasMany
    {
        return $this->hasMany(Reminder::class);
    }

    /**
     * Health share tokens generated by this user.
     */
    public function healthShareTokens(): HasMany
    {
        return $this->hasMany(HealthShareToken::class);
    }

    /**
     * Pet reports submitted by this user (as the reporter).
     */
    public function petReports(): HasMany
    {
        return $this->hasMany(PetReport::class, 'reporter_id');
    }

    /**
     * Pet reports reviewed by this user (as an admin).
     */
    public function reviewedPetReports(): HasMany
    {
        return $this->hasMany(PetReport::class, 'reviewed_by');
    }

    // ---------- Admin helpers ----------

    /**
     * Count pets belonging to this user (including soft-deleted).
     */
    public function petsCount(): int
    {
        return $this->pets()->withTrashed()->count();
    }

    /**
     * Count health records across all this user's pets.
     */
    public function healthRecordsCount(): int
    {
        return \App\Models\HealthRecord::whereIn('pet_id', $this->pets()->withTrashed()->pluck('id'))->count();
    }

    /**
     * Count vaccinations across all this user's pets.
     */
    public function vaccinationsCount(): int
    {
        return \App\Models\Vaccination::whereIn('pet_id', $this->pets()->withTrashed()->pluck('id'))->count();
    // ==================== RELATIONSHIPS ====================

    /**
     * Businesses owned by this user.
     */
    public function businesses(): HasMany
    {
        return $this->hasMany(Business::class);
    }

    public function products(): HasMany
{
    return $this->hasMany(Product::class);
}

public function productCategories(): HasMany  // if you want user-specific
{
    return $this->hasMany(ProductCategory::class);
}

public function petSaleListings(): HasMany
{
    return $this->hasMany(PetSaleListing::class);
}

    /**
     * Businesses approved by this user (as admin).
     */
    public function approvedBusinesses(): HasMany
    {
        return $this->hasMany(Business::class, 'approved_by');
    }
}